---
driver:
  name: vagrant
<% if ENV['TEAMCITY'] == '1' %>
  synced_folders:
    - ['.junit', '/.junit']
<% end %>

driver_config:
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: debian-6.0.10
    run_list:
    - recipe[apt::default]
  - name: debian-7.8
    run_list:
    - recipe[apt::default]
  - name: centos-6.6
    run_list:
    - recipe[yum::default]
  - name: centos-7.0
    run_list:
    - recipe[yum::default]
  - name: opentable/win-2008r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    run_list:
    - recipe[windows::default]
    transport:
      name: winrm
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    run_list:
    - recipe[windows::default]
    transport:
      name: winrm

suites:
  - name: lwrp_resources
    run_list:
      - recipe[test::kitchen_log_file]
    attributes:
    
  - name: attribute_resources_linux
    run_list:
      - recipe[test::kitchen_log_file_attrs]
    excludes:
      - opentable/win-2012r2-standard-amd64-nocm
      - opentable/win-2008r2-standard-amd64-nocm
    verifier:
      suite_name: attribute_resources
    attributes:
      nxlog:
        destinations:
          test:
            file: /var/log/nxlog/test.log
          test_2:
            file: /var/log/nxlog/test2.log
            default: true
          test_om_file_2:
            file: /var/log/nxlog/mark3.log
        papertrails:
          papertrail:
            port: 17992
            host: logs2
            default: true
        sources:
          mark:
            input_module: im_mark
            mark_interval: 1
            mark: -> -> MARK <- <-
            destination:
              - test
              - defaults

  - name: attribute_resources_windows
    run_list:
      - recipe[test::kitchen_log_file_attrs]
    includes:
      - opentable/win-2012r2-standard-amd64-nocm
      - opentable/win-2008r2-standard-amd64-nocm
    verifier:
      suite_name: attribute_resources
    attributes:
      nxlog:
        destinations:
          test:
            file: c:/windows/temp/test.log
          test_2:
            file: c:/windows/temp/test2.log
            default: true
          test_om_file_2:
            file: c:/windows/temp/mark3.log
        papertrails:
          papertrail:
            port: 17992
            host: logs2
            default: true
        sources:
          mark:
            input_module: im_mark
            mark_interval: 1
            mark: -> -> MARK <- <-
            destination:
              - test
              - defaults

  - name: syslog
    run_list:
      - recipe[test::kitchen_syslog]
    excludes:
      - opentable/win-2012r2-standard-amd64-nocm
      - opentable/win-2008r2-standard-amd64-nocm
    attributes:
      nxlog:
        syslog:
          destinations: ['test']
